"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "vi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const TRANSLATIONS: Record<Language, Record<string, Record<string, string>>> = {
  en: {
    sidebar: {
      "Observe": "Observe",
      "Build": "Build",
      "Protect & Connect": "Protect & Connect",
      "Account Management": "Account Management",
      "Home": "Home",
      "Recents": "Recents",
      "Investigate": "Investigate",
      "Analytics": "Analytics",
      "Workers & Pages": "Workers & Pages",
      "AI": "AI",
      "Storage & databases": "Storage & databases",
      "Media & images": "Media & images",
      "Application security": "Application security",
      "Zero Trust": "Zero Trust",
      "Turnstile": "Turnstile",
      "DNS": "DNS",
      "Manage account": "Manage account",
      "Members": "Members",
      "Billing": "Billing",
      "Account API tokens": "Account API tokens",
      "OAuth clients": "OAuth clients",
      "Audit logs": "Audit logs",
      "Notifications": "Notifications",
      "Shared config": "Shared config",
      "Blocked content": "Blocked content",
      "Abuse reports": "Abuse reports",
      "Carbon Impact Report": "Carbon Impact Report",
      "Configurations": "Configurations",
      "Tagged Resources": "Tagged Resources",
      "Overview": "Overview",
      "WAF": "WAF",
      "Security insights": "Security insights",
      "Plans": "Plans",
      "KV": "KV",
      "D1": "D1",
      "R2": "R2",
      "Images Optimization": "Images Optimization",
      "Stream": "Stream",
      "R2 Object Storage": "R2 Object Storage",
      "D1 Databases": "D1 Databases",
      "Delivery & performance": "Delivery & performance",
      "Networking": "Networking",
      "Insights": "Insights",
      "Tunnels": "Tunnels",
      "Mesh": "Mesh",
      "Routes": "Routes",
      "IP addresses": "IP addresses",
      "Caching": "Caching",
      "Speed": "Speed",
      "Load Balancing": "Load Balancing",
      "Redirects": "Redirects",
      "Dashboard": "Dashboard"
    },
    header: {
      "Support Portal": "Support Portal",
      "Ask AI": "Ask AI",
      "Help Center": "Help Center",
      "Logged in as": "Logged in as",
      "Account Home": "Account Home",
      "Profile": "Profile",
      "Appearance": "Appearance",
      "Language": "Language",
      "Timezone": "Timezone",
      "Log out": "Log out"
    },
    common: {
      "Upgrade": "Upgrade",
      "Search": "Search",
      "Cancel": "Cancel",
      "Create": "Create",
      "Save": "Save",
      "Delete": "Delete",
      "Status": "Status"
    },
    dash_home: {
      "Home": "Home",
      "Websites": "Websites",
      "Search websites...": "Search websites...",
      "Add a site": "Add a site",
      "Domain name": "Domain name",
      "Status": "Status",
      "Active": "Active",
      "Pending Nameserver Update": "Pending Nameserver Update",
      "No websites found": "No websites found",
      "Try adjusting your search terms or add a new website to manage.": "Try adjusting your search terms or add a new website to manage.",
      "Discover": "Discover",
      "Build serverless with Workers": "Build serverless with Workers",
      "Deploy serverless code instantly to the Cloudflare network. No servers to configure or maintain.": "Deploy serverless code instantly to the Cloudflare network. No servers to configure or maintain.",
      "Create a Worker": "Create a Worker",
      "Secure traffic with Zero Trust": "Secure traffic with Zero Trust",
      "Stop data loss, manage employee access, and secure networks at remote scale.": "Stop data loss, manage employee access, and secure networks at remote scale.",
      "Configure Gateway": "Configure Gateway",
      "Resources": "Resources",
      "Cloudflare API Reference": "Cloudflare API Reference",
      "Manage configuration via automated REST API endpoints.": "Manage configuration via automated REST API endpoints.",
      "Developer Documentation": "Developer Documentation",
      "Guides, tutorials, and templates for building on Cloudflare.": "Guides, tutorials, and templates for building on Cloudflare.",
      "Community Forum": "Community Forum",
      "Connect with fellow engineers and developer teams.": "Connect with fellow engineers and developer teams.",
      "System Status": "System Status",
      "Check current operational uptime of Cloudflare edge services.": "Check current operational uptime of Cloudflare edge services.",
      "Add a site to Cloudflare": "Add a site to Cloudflare",
      "Enter your site's apex domain name (e.g., example.com) to begin setup.": "Enter your site's apex domain name (e.g., example.com) to begin setup.",
      "Site address (domain name)": "Site address (domain name)",
      "Note: In this emulation template, clicking \"Add site\" is a visual demo only. The new domain will not persist to the active list.": "Note: In this emulation template, clicking \"Add site\" is a visual demo only. The new domain will not persist to the active list.",
      "Add site": "Add site"
    },
    dash_dns: {
      "DNS Management": "DNS Management",
      "Configure DNS records for routing traffic, verifying domain ownership, or setting up mail delivery.": "Configure DNS records for routing traffic, verifying domain ownership, or setting up mail delivery.",
      "Cancel Add": "Cancel Add",
      "Add record": "Add record",
      "Add new DNS record": "Add new DNS record",
      "Type": "Type",
      "Name (e.g. @ or www)": "Name (e.g. @ or www)",
      "IPv4 Address": "IPv4 Address",
      "Mail Server (Content)": "Mail Server (Content)",
      "Target": "Target",
      "TTL": "TTL",
      "Proxy status": "Proxy status",
      "Proxied": "Proxied",
      "DNS only": "DNS only",
      "Search DNS records...": "Search DNS records...",
      "Search records...": "Search records...",
      "DNS Records": "DNS Records",
      "Content": "Content",
      "Cloudflare Tunnels": "Cloudflare Tunnels",
      "Magic WAN & Connectivity Mesh": "Magic WAN & Connectivity Mesh",
      "Static Routing & virtual networks": "Static Routing & virtual networks",
      "IP Prefixes & BGP Routing": "IP Prefixes & BGP Routing",
      "Caching & speed optimization": "Caching & speed optimization",
      "Load Balancing": "Load Balancing",
      "Redirect Rules": "Redirect Rules",
      "Active": "Active",
      "Inactive": "Inactive",
      "Degraded": "Degraded",
      "Accelerate performance and protect with Cloudflare proxy routing.": "Accelerate performance and protect with Cloudflare proxy routing.",
      "Proxying is not supported for TXT and MX record types.": "Proxying is not supported for TXT and MX record types.",
      "Save record": "Save record",
      "Actions": "Actions",
      "No DNS records match your query.": "No DNS records match your query.",
      "Total DNS Queries": "Total DNS Queries",
      "Over the last 24 hours": "Over the last 24 hours",
      "Average Response Time": "Average Response Time",
      "Inspected from Anycast edge": "Inspected from Anycast edge",
      "Query Success Rate": "Query Success Rate",
      "No resolution errors registered": "No resolution errors registered",
      "Cached Queries Ratio": "Cached Queries Ratio",
      "Resolved from local edge cache": "Resolved from local edge cache",
      "Query Volume Breakdown by Type": "Query Volume Breakdown by Type",
      "A (IPv4 Host Mapping)": "A (IPv4 Host Mapping)",
      "CNAME (Canonical Aliases)": "CNAME (Canonical Aliases)",
      "TXT (Domain Verifications)": "TXT (Domain Verifications)",
      "MX (Mail Exchange Exchange)": "MX (Mail Exchange Exchange)",
      "Response Codes Metrics": "Response Codes Metrics",
      "NOERROR (Successfully Resolved)": "NOERROR (Successfully Resolved)",
      "NXDOMAIN (Domain Not Found)": "NXDOMAIN (Domain Not Found)",
      "SERVFAIL (Nameserver Error)": "SERVFAIL (Nameserver Error)",
      "REFUSED (Query Rejected)": "REFUSED (Query Rejected)",
      "Cloudflare Tunnels (Argo Tunnel)": "Cloudflare Tunnels (Argo Tunnel)",
      "Connect your origin server directly to the Cloudflare network without opening public ports or configuring firewall rules.": "Connect your origin server directly to the Cloudflare network without opening public ports or configuring firewall rules.",
      "Create a Tunnel": "Create a Tunnel",
      "Name Your Tunnel": "Name Your Tunnel",
      "Tunnel Name": "Tunnel Name",
      "e.g. production-origin-daemon": "e.g. production-origin-daemon",
      "Save Tunnel": "Save Tunnel",
      "Tunnel ID (UUID)": "Tunnel ID (UUID)",
      "Active Connectors": "Active Connectors",
      "Created Date": "Created Date",
      "Create secure, fast connectivity meshes between office locations, data centers, and cloud infrastructure.": "Create secure, fast connectivity meshes between office locations, data centers, and cloud infrastructure.",
      "Overlay Connections": "Overlay Connections",
      "Healthy mesh topology": "Healthy mesh topology",
      "Magic Tunnels (GRE/IPsec)": "Magic Tunnels (GRE/IPsec)",
      "Direct interconnect fibers mapped": "Direct interconnect fibers mapped",
      "Total Routed Volume": "Total Routed Volume",
      "Transferred over Anycast WAN": "Transferred over Anycast WAN",
      "Simulated Mesh Connection Nodes": "Simulated Mesh Connection Nodes",
      "HQ Office (San Francisco)": "HQ Office (San Francisco)",
      "AWS Virtual Private Cloud (us-east-1)": "AWS Virtual Private Cloud (us-east-1)",
      "EU Branch (London Hub)": "EU Branch (London Hub)",
      "CONNECTED": "CONNECTED",
      "Manage network level routes and static routing policies for internal Anycast prefixes.": "Manage network level routes and static routing policies for internal Anycast prefixes.",
      "Add Route": "Add Route",
      "CIDR Destination": "CIDR Destination",
      "Gateway Interface": "Gateway Interface",
      "Priority Metric": "Priority Metric",
      "Route status": "Route status",
      "Advertise or withdraw your own BYOIP (Bring Your Own IP) subnet prefixes to Cloudflare Anycast edge.": "Advertise or withdraw your own BYOIP (Bring Your Own IP) subnet prefixes to Cloudflare Anycast edge.",
      "Register Prefix": "Register Prefix",
      "Subnet Prefix": "Subnet Prefix",
      "ASN Assignment": "ASN Assignment",
      "BGP Status": "BGP Status",
      "Advertisement status": "Advertisement status",
      "Purge Cache": "Purge Cache",
      "Clear cached files instantly from the Cloudflare edge network to force requests to fetch the newest version from your origin.": "Clear cached files instantly from the Cloudflare edge network to force requests to fetch the newest version from your origin.",
      "Purge Everything": "Purge Everything",
      "Purge Individual Paths": "Purge Individual Paths",
      "Cache Level Settings": "Cache Level Settings",
      "Determine how much of your website's static contents Cloudflare will cache at the edge.": "Determine how much of your website's static contents Cloudflare will cache at the edge.",
      "Global Cache Hit Ratio (24h)": "Global Cache Hit Ratio (24h)",
      "Auto Minify Codes": "Auto Minify Codes",
      "Remove unnecessary characters (such as comments and whitespaces) from web page source code to reduce transfer size.": "Remove unnecessary characters (such as comments and whitespaces) from web page source code to reduce transfer size.",
      "HTML Minification": "HTML Minification",
      "CSS Minification": "CSS Minification",
      "JavaScript Minification": "JavaScript Minification",
      "Performance Optimization": "Performance Optimization",
      "Brotli Compression": "Brotli Compression",
      "Speed up page load times using Brotli compression.": "Speed up page load times using Brotli compression.",
      "Rocket Loader™": "Rocket Loader™",
      "Improve paint times for pages containing JavaScript.": "Improve paint times for pages containing JavaScript.",
      "Simulated Performance Score Boost": "Simulated Performance Score Boost",
      "Global Load Balancer & Origin Pools": "Global Load Balancer & Origin Pools",
      "Distribute request traffic across multiple origin servers with active health checking.": "Distribute request traffic across multiple origin servers with active health checking.",
      "Create Balancer": "Create Balancer",
      "Origin Pool Name": "Origin Pool Name",
      "Endpoint Target": "Endpoint Target",
      "Health Path Check": "Health Path Check",
      "Pool status": "Pool status",
      "URL Redirect Page Rules": "URL Redirect Page Rules",
      "Map request paths to new target URLs using 301 Permanent or 302 Temporary redirects.": "Map request paths to new target URLs using 301 Permanent or 302 Temporary redirects.",
      "Add Page Rule": "Add Page Rule",
      "Source Route Match": "Source Route Match",
      "Destination Route Target": "Destination Route Target",
      "Redirect Type": "Redirect Type",
      "Rule status": "Rule status"
    },
    dash_analytics: {
      "Analytics & Logs": "Analytics & Logs",
      "Web Traffic Analytics": "Web Traffic Analytics",
      "Real-time overview of visitor traffic, request volume, and bandwidth performance.": "Real-time overview of visitor traffic, request volume, and bandwidth performance.",
      "Select Domain": "Select Domain",
      "Summary Metrics (Last 24 Hours)": "Summary Metrics (Last 24 Hours)",
      "Total Requests": "Total Requests",
      "Unique Visitors": "Unique Visitors",
      "Data Transferred": "Data Transferred",
      "Page Views": "Page Views",
      "Traffic Volume (Requests vs Visitors)": "Traffic Volume (Requests vs Visitors)",
      "Requests (line)": "Requests (line)",
      "Visitors (bar)": "Visitors (bar)",
      "Web requests": "Web requests",
      "Unique visitors": "Unique visitors",
      "Traffic by Country / Region": "Traffic by Country / Region",
      "Top sources of geographic traffic requests to your domains.": "Top sources of geographic traffic requests to your domains.",
      "Country / Region": "Country / Region",
      "United States": "United States",
      "Singapore": "Singapore",
      "Germany": "Germany",
      "Vietnam": "Vietnam",
      "Japan": "Japan",
      "Percentage": "Percentage"
    },
    dash_security: {
      "WAF & Application Security": "WAF & Application Security",
      "Configure Web Application Firewall (WAF), review threat analytics, or setup CAPTCHA Turnstile widgets.": "Configure Web Application Firewall (WAF), review threat analytics, or setup CAPTCHA Turnstile widgets.",
      "WAF Rules": "WAF Rules",
      "Threat Analytics": "Threat Analytics",
      "WAF Rules & Firewall Policies": "WAF Rules & Firewall Policies",
      "Block, challenge, or log incoming web requests matching specific criteria.": "Block, challenge, or log incoming web requests matching specific criteria.",
      "Add firewall rule": "Add firewall rule",
      "Search rules...": "Search rules...",
      "Rule Name": "Rule Name",
      "Expression / Criteria": "Expression / Criteria",
      "Action": "Action",
      "Enabled": "Enabled",
      "Block": "Block",
      "Challenge": "Challenge",
      "Log": "Log",
      "Threat Intel & Analytics": "Threat Intel & Analytics",
      "Visual display of blocked traffic events and DDoS mitigation activity.": "Visual display of blocked traffic events and DDoS mitigation activity.",
      "Events Mitigated": "Events Mitigated",
      "DDoS Threats Blocked": "DDoS Threats Blocked",
      "Security Insight Score": "Security Insight Score",
      "Excellent": "Excellent",
      "Mitigated Security Events": "Mitigated Security Events"
    },
    dash_workers: {
      "Workers & Pages": "Workers & Pages",
      "Deploy serverless code, deploy static sites via Git workflows, or manage global Cron Triggers.": "Deploy serverless code, deploy static sites via Git workflows, or manage global Cron Triggers.",
      "Create Application": "Create Application",
      "Serverless Functions": "Serverless Functions",
      "Static Sites": "Static Sites",
      "Cron Triggers": "Cron Triggers",
      "Manage serverless scripts running directly on the edge.": "Manage serverless scripts running directly on the edge.",
      "Status": "Status",
      "Requests (24h)": "Requests (24h)",
      "Active": "Active",
      "Deploy static frontends using Cloudflare global CDN.": "Deploy static frontends using Cloudflare global CDN.",
      "Repository": "Repository",
      "Branch": "Branch",
      "Last Deploy": "Last Deploy",
      "Configure automated timers to invoke serverless logic periodically.": "Configure automated timers to invoke serverless logic periodically.",
      "Interval": "Interval",
      "Every minute": "Every minute",
      "Every 5 minutes": "Every 5 minutes",
      "Every hour": "Every hour",
      "Daily": "Daily",
      "Target Script": "Target Script"
    },
    dash_storage: {
      "Storage & Databases": "Storage & Databases",
      "Store global application data using key-value stores, relational SQL, or large object buckets.": "Store global application data using key-value stores, relational SQL, or large object buckets.",
      "KV Namespace": "KV Namespace",
      "SQL Database": "SQL Database",
      "Object Bucket": "Object Bucket",
      "Namespace ID": "Namespace ID",
      "Keys Count": "Keys Count",
      "Database Name": "Database Name",
      "Size": "Size",
      "Bucket Name": "Bucket Name",
      "Objects Count": "Objects Count",
      "Create Namespace": "Create Namespace",
      "Create Database": "Create Database",
      "Create Bucket": "Create Bucket",
      "Active": "Active",
      "Storage": "Storage",
      "Manage storage": "Manage storage"
    },
    dash_ai: {
      "Workers AI Hub": "Workers AI Hub",
      "Run serverless AI models on Cloudflare GPU network. Connect to LLMs, image generation, and translation instantly.": "Run serverless AI models on Cloudflare GPU network. Connect to LLMs, image generation, and translation instantly.",
      "Chat with Model": "Chat with Model",
      "Run Inference": "Run Inference",
      "Select AI Model": "Select AI Model",
      "System Prompt": "System Prompt",
      "User Input": "User Input",
      "Generate Response": "Generate Response",
      "Generation Progress": "Generation Progress",
      "Result Output": "Result Output",
      "Ready for inference.": "Ready for inference.",
      "Running AI inference...": "Running AI inference..."
    },
    dash_media: {
      "Media & Images": "Media & Images",
      "Optimize images and stream video content across the global Anycast network.": "Optimize images and stream video content across the global Anycast network.",
      "Stream Videos": "Stream Videos",
      "Optimize Images": "Optimize Images",
      "Video Title": "Video Title",
      "Duration": "Duration",
      "Uploaded": "Uploaded",
      "File Size": "File Size",
      "Status": "Status",
      "Ready": "Ready",
      "Processing": "Processing",
      "Image Name": "Image Name",
      "Dimensions": "Dimensions",
      "Format": "Format",
      "Compression Ratio": "Compression Ratio"
    },
    dash_zero_trust: {
      "Zero Trust Services": "Zero Trust Services",
      "Configure edge secure gateway, coordinate remote access control policies, and audit network logs.": "Configure edge secure gateway, coordinate remote access control policies, and audit network logs.",
      "Access Control Policies": "Access Control Policies",
      "Audit logs": "Audit logs",
      "Search policies...": "Search policies...",
      "Policy Name": "Policy Name",
      "Target Application": "Target Application",
      "Allowed Groups": "Allowed Groups",
      "Action": "Action",
      "Allow": "Allow",
      "Bypass": "Bypass",
      "Audit Activity Logs": "Audit Activity Logs",
      "Timestamp": "Timestamp",
      "Actor": "Actor",
      "Resource": "Resource",
      "Success": "Success",
      "Failed": "Failed"
    },
    dash_manage_account: {
      "Manage Account": "Manage Account",
      "Configure account settings, manage members, billing subscriptions, API tokens, and view audits.": "Configure account settings, manage members, billing subscriptions, API tokens, and view audits.",
      "Members": "Members",
      "Billing": "Billing",
      "Audit Logs": "Audit Logs",
      "Invite Member": "Invite Member",
      "Search members...": "Search members...",
      "Email Address": "Email Address",
      "Role": "Role",
      "Status": "Status",
      "Administrator": "Administrator",
      "Developer": "Developer",
      "Billing Admin": "Billing Admin",
      "Active": "Active",
      "Pending Invitation": "Pending Invitation",
      "Invite": "Invite",
      "Invite members": "Invite members",
      "Billing Subscriptions": "Billing Subscriptions",
      "Invoice Number": "Invoice Number",
      "Date": "Date",
      "Amount": "Amount",
      "Paid": "Paid",
      "Search audit logs...": "Search audit logs...",
      "Event Name": "Event Name",
      "IP Address": "IP Address"
    },
    dash_investigate: {
      "Investigate & Threat Center": "Investigate & Threat Center",
      "Analyze threat intelligence databases, run scanning actions, and review reputation profiles.": "Analyze threat intelligence databases, run scanning actions, and review reputation profiles.",
      "Run Threat Scan": "Run Threat Scan",
      "Domain or IP Address": "Domain or IP Address",
      "Scan": "Scan",
      "Scanning in progress...": "Scanning in progress..."
    },
    dash_settings: {
      "Account Settings": "Account Settings",
      "Manage account configurations, notification rules, and preferences.": "Manage account configurations, notification rules, and preferences.",
      "Account Name": "Account Name",
      "Notification Settings": "Notification Settings"
    },
    dash_profile: {
      "User Profile": "User Profile",
      "Manage personal account profile, authentication preferences, and active sessions.": "Manage personal account profile, authentication preferences, and active sessions.",
      "Email Address": "Email Address",
      "Language Preference": "Language Preference",
      "Change Password": "Change Password"
    },
    dash_plans: {
      "Plans & Pricing": "Plans & Pricing",
      "Review current plans or upgrade to access advanced delivery, performance, and security features.": "Review current plans or upgrade to access advanced delivery, performance, and security features.",
      "Free Plan": "Free Plan",
      "Pro Plan": "Pro Plan",
      "Business Plan": "Business Plan",
      "Enterprise Plan": "Enterprise Plan",
      "Current Plan": "Current Plan",
      "Upgrade": "Upgrade"
    },
    dash_recents: {
      "Recent Activity": "Recent Activity",
      "Timeline of recent actions and status changes on your account resources.": "Timeline of recent actions and status changes on your account resources."
    }
  },
  vi: {
    sidebar: {
      "Observe": "Quan sát",
      "Build": "Xây dựng",
      "Protect & Connect": "Bảo vệ & Kết nối",
      "Account Management": "Quản lý tài khoản",
      "Home": "Trang chủ",
      "Recents": "Gần đây",
      "Investigate": "Điều tra & Quét mối đe dọa",
      "Analytics": "Phân tích số liệu",
      "Workers & Pages": "Workers & Pages",
      "AI": "AI",
      "Storage & databases": "Lưu trữ & Cơ sở dữ liệu",
      "Media & images": "Truyền thông & Hình ảnh",
      "Application security": "Bảo mật ứng dụng",
      "Zero Trust": "Zero Trust",
      "Turnstile": "Turnstile CAPTCHA",
      "DNS": "DNS",
      "Manage account": "Quản trị tài khoản",
      "Members": "Thành viên & Quyền truy cập",
      "Billing": "Thanh toán & Gói cước",
      "Account API tokens": "Token API tài khoản",
      "OAuth clients": "Ứng dụng khách OAuth",
      "Audit logs": "Nhật ký kiểm tra",
      "Notifications": "Thông báo hệ thống",
      "Shared config": "Cấu hình chia sẻ",
      "Blocked content": "Nội dung bị chặn",
      "Abuse reports": "Báo cáo lạm dụng",
      "Carbon Impact Report": "Báo cáo tác động Carbon",
      "Configurations": "Cấu hình hệ thống",
      "Tagged Resources": "Tài nguyên được gắn thẻ",
      "Overview": "Tổng quan",
      "WAF": "WAF",
      "Security insights": "Thông tin bảo mật",
      "Plans": "Gói dịch vụ",
      "KV": "KV",
      "D1": "D1",
      "R2": "Lưu trữ đối tượng R2",
      "Images Optimization": "Tối ưu hóa hình ảnh",
      "Stream": "Stream",
      "R2 Object Storage": "Lưu trữ đối tượng R2",
      "D1 Databases": "Cơ sở dữ liệu D1",
      "Delivery & performance": "Phân phối & Hiệu năng",
      "Networking": "Mạng & Kết nối",
      "Insights": "Thông tin chi tiết",
      "Tunnels": "Đường hầm",
      "Mesh": "Mạng lưới",
      "Routes": "Định tuyến",
      "IP addresses": "Địa chỉ IP",
      "Caching": "Bộ nhớ đệm",
      "Speed": "Tối ưu tốc độ",
      "Load Balancing": "Cân bằng tải",
      "Redirects": "Chuyển hướng",
      "Dashboard": "Bảng điều khiển"
    },
    header: {
      "Support Portal": "Cổng Hỗ trợ",
      "Ask AI": "Hỏi trợ lý AI",
      "Help Center": "Trung tâm hỗ trợ",
      "Logged in as": "Đăng nhập bằng",
      "Account Home": "Trang chủ tài khoản",
      "Profile": "Thông tin cá nhân",
      "Appearance": "Giao diện hiển thị",
      "Language": "Ngôn ngữ hệ thống",
      "Timezone": "Múi giờ hiển thị",
      "Log out": "Đăng xuất tài khoản"
    },
    common: {
      "Upgrade": "Nâng cấp gói",
      "Search": "Tìm kiếm...",
      "Cancel": "Hủy bỏ",
      "Create": "Tạo mới",
      "Save": "Lưu thay đổi",
      "Delete": "Xóa bỏ",
      "Status": "Trạng thái"
    },
    dash_home: {
      "Home": "Trang chủ",
      "Websites": "Các trang web",
      "Search websites...": "Tìm kiếm trang web...",
      "Add a site": "Thêm trang web",
      "Domain name": "Tên miền",
      "Status": "Trạng thái",
      "Active": "Hoạt động",
      "Pending Nameserver Update": "Đang cập nhật Nameserver",
      "No websites found": "Không tìm thấy trang web nào",
      "Try adjusting your search terms or add a new website to manage.": "Thử điều chỉnh từ khóa tìm kiếm hoặc thêm trang web mới để quản lý.",
      "Discover": "Khám phá",
      "Build serverless with Workers": "Xây dựng serverless với Workers",
      "Deploy serverless code instantly to the Cloudflare network. No servers to configure or maintain.": "Triển khai mã nguồn serverless tức thì lên mạng lưới Cloudflare. Không cần cấu hình hay bảo trì máy chủ.",
      "Create a Worker": "Tạo một Worker",
      "Secure traffic with Zero Trust": "Bảo mật lưu lượng với Zero Trust",
      "Stop data loss, manage employee access, and secure networks at remote scale.": "Ngăn chặn thất thoát dữ liệu, quản lý truy cập của nhân viên và bảo mật mạng lưới từ xa.",
      "Configure Gateway": "Cấu hình Gateway",
      "Resources": "Tài nguyên",
      "Cloudflare API Reference": "Tham chiếu API Cloudflare",
      "Manage configuration via automated REST API endpoints.": "Quản lý cấu hình thông qua các điểm cuối REST API tự động.",
      "Developer Documentation": "Tài liệu dành cho lập trình viên",
      "Guides, tutorials, and templates for building on Cloudflare.": "Hướng dẫn, bài học thực hành và các mẫu để xây dựng trên Cloudflare.",
      "Community Forum": "Diễn đàn cộng đồng",
      "Connect with fellow engineers and developer teams.": "Kết nối với các kỹ sư và đội ngũ phát triển khác.",
      "System Status": "Trạng thái hệ thống",
      "Check current operational uptime of Cloudflare edge services.": "Kiểm tra thời gian hoạt động của các dịch vụ biên Cloudflare.",
      "Add a site to Cloudflare": "Thêm trang web vào Cloudflare",
      "Enter your site's apex domain name (e.g., example.com) to begin setup.": "Nhập tên miền chính của trang web (ví dụ: example.com) để bắt đầu thiết lập.",
      "Site address (domain name)": "Địa chỉ trang web (tên miền)",
      "Note: In this emulation template, clicking \"Add site\" is a visual demo only. The new domain will not persist to the active list.": "Lưu ý: Trong giao diện mô phỏng này, việc nhấn nút \"Thêm trang web\" chỉ mang tính chất minh họa. Tên miền mới sẽ không được lưu vào danh sách hoạt động.",
      "Add site": "Thêm trang"
    },
    dash_dns: {
      "DNS Management": "Quản lý DNS",
      "Configure DNS records for routing traffic, verifying domain ownership, or setting up mail delivery.": "Cấu hình các bản ghi DNS để định tuyến lưu lượng truy cập, xác minh quyền sở hữu tên miền hoặc thiết lập gửi email.",
      "Cancel Add": "Hủy thêm",
      "Add record": "Thêm bản ghi",
      "Add new DNS record": "Thêm bản ghi DNS mới",
      "Type": "Loại",
      "Name (e.g. @ or www)": "Tên (ví dụ: @ hoặc www)",
      "IPv4 Address": "Địa chỉ IPv4",
      "Mail Server (Content)": "Máy chủ thư (Nội dung)",
      "Target": "Đích đến",
      "TTL": "TTL",
      "Proxy status": "Trạng thái proxy",
      "Proxied": "Được proxy",
      "DNS only": "Chỉ DNS",
      "Search DNS records...": "Tìm kiếm bản ghi DNS...",
      "Search records...": "Tìm kiếm các bản ghi...",
      "DNS Records": "Các bản ghi DNS",
      "Content": "Nội dung",
      "Cloudflare Tunnels": "Đường hầm Cloudflare (Tunnels)",
      "Magic WAN & Connectivity Mesh": "Mạng lưới kết nối & Magic WAN",
      "Static Routing & virtual networks": "Định tuyến tĩnh & Mạng ảo",
      "IP Prefixes & BGP Routing": "Tiền tố IP & Định tuyến BGP",
      "Caching & speed optimization": "Tối ưu hóa bộ nhớ đệm & tốc độ",
      "Load Balancing": "Cân bằng tải",
      "Redirect Rules": "Quy tắc chuyển hướng",
      "Active": "Hoạt động",
      "Inactive": "Không hoạt động",
      "Degraded": "Bị suy giảm",
      "Accelerate performance and protect with Cloudflare proxy routing.": "Tăng tốc hiệu năng và bảo vệ với định tuyến proxy của Cloudflare.",
      "Proxying is not supported for TXT and MX record types.": "Không hỗ trợ proxy cho các loại bản ghi TXT và MX.",
      "Save record": "Lưu bản ghi",
      "Actions": "Hành động",
      "No DNS records match your query.": "Không có bản ghi DNS nào khớp với tìm kiếm của bạn.",
      "Total DNS Queries": "Tổng số truy vấn DNS",
      "Over the last 24 hours": "Trong 24 giờ qua",
      "Average Response Time": "Thời gian phản hồi trung bình",
      "Inspected from Anycast edge": "Đo từ máy chủ biên Anycast",
      "Query Success Rate": "Tỷ lệ truy vấn thành công",
      "No resolution errors registered": "Không ghi nhận lỗi phân giải nào",
      "Cached Queries Ratio": "Tỷ lệ truy vấn được lưu đệm",
      "Resolved from local edge cache": "Được phân giải từ bộ đệm biên cục bộ",
      "Query Volume Breakdown by Type": "Thống kê lượng truy vấn theo loại",
      "A (IPv4 Host Mapping)": "A (Bản đồ máy chủ IPv4)",
      "CNAME (Canonical Aliases)": "CNAME (Bí danh chuẩn hóa)",
      "TXT (Domain Verifications)": "TXT (Xác minh tên miền)",
      "MX (Mail Exchange Exchange)": "MX (Trao đổi máy chủ thư)",
      "Response Codes Metrics": "Chỉ số mã phản hồi",
      "NOERROR (Successfully Resolved)": "NOERROR (Phân giải thành công)",
      "NXDOMAIN (Domain Not Found)": "NXDOMAIN (Không tìm thấy tên miền)",
      "SERVFAIL (Nameserver Error)": "SERVFAIL (Lỗi Nameserver)",
      "REFUSED (Query Rejected)": "REFUSED (Truy vấn bị từ chối)",
      "Cloudflare Tunnels (Argo Tunnel)": "Đường hầm Cloudflare (Argo Tunnel)",
      "Connect your origin server directly to the Cloudflare network without opening public ports or configuring firewall rules.": "Kết nối trực tiếp máy chủ gốc của bạn với mạng Cloudflare mà không cần mở cổng công khai hoặc cấu hình quy tắc tường lửa.",
      "Create a Tunnel": "Tạo đường hầm (Tunnel)",
      "Name Your Tunnel": "Đặt tên cho đường hầm của bạn",
      "Tunnel Name": "Tên đường hầm",
      "e.g. production-origin-daemon": "Ví dụ: production-origin-daemon",
      "Save Tunnel": "Lưu đường hầm",
      "Tunnel ID (UUID)": "ID đường hầm (UUID)",
      "Active Connectors": "Bộ kết nối hoạt động",
      "Created Date": "Ngày tạo",
      "Create secure, fast connectivity meshes between office locations, data centers, and cloud infrastructure.": "Tạo các mạng lưới kết nối nhanh, bảo mật giữa các địa điểm văn phòng, trung tâm dữ liệu và cơ sở hạ tầng đám mây.",
      "Overlay Connections": "Kết nối Overlay",
      "Healthy mesh topology": "Cấu trúc mạng lưới khỏe mạnh",
      "Magic Tunnels (GRE/IPsec)": "Đường hầm Magic (GRE/IPsec)",
      "Direct interconnect fibers mapped": "Đã ánh xạ sợi kết nối trực tiếp",
      "Total Routed Volume": "Tổng lưu lượng định tuyến",
      "Transferred over Anycast WAN": "Được truyền qua Anycast WAN",
      "Simulated Mesh Connection Nodes": "Các nút kết nối mạng lưới mô phỏng",
      "HQ Office (San Francisco)": "Văn phòng HQ (San Francisco)",
      "AWS Virtual Private Cloud (us-east-1)": "Đám mây riêng ảo AWS (us-east-1)",
      "EU Branch (London Hub)": "Chi nhánh EU (London Hub)",
      "CONNECTED": "ĐÃ KẾT NỐI",
      "Manage network level routes and static routing policies for internal Anycast prefixes.": "Quản lý các tuyến đường cấp mạng và chính sách định tuyến tĩnh cho các tiền tố Anycast nội bộ.",
      "Add Route": "Thêm tuyến đường",
      "CIDR Destination": "CIDR Đích",
      "Gateway Interface": "Giao diện Gateway",
      "Priority Metric": "Chỉ số ưu tiên",
      "Route status": "Trạng thái tuyến đường",
      "Advertise or withdraw your own BYOIP (Bring Your Own IP) subnet prefixes to Cloudflare Anycast edge.": "Quảng bá hoặc thu hồi các tiền tố mạng con BYOIP (Mang IP của riêng bạn) của bạn tới biên Anycast của Cloudflare.",
      "Register Prefix": "Đăng ký tiền tố",
      "Subnet Prefix": "Tiền tố mạng con",
      "ASN Assignment": "Gán ASN",
      "BGP Status": "Trạng thái BGP",
      "Advertisement status": "Trạng thái quảng bá",
      "Purge Cache": "Xóa bộ nhớ đệm (Purge)",
      "Clear cached files instantly from the Cloudflare edge network to force requests to fetch the newest version from your origin.": "Xóa ngay lập tức các tệp được lưu trong bộ nhớ đệm khỏi mạng biên Cloudflare để buộc các yêu cầu tìm nạp phiên bản mới nhất từ máy chủ gốc của bạn.",
      "Purge Everything": "Xóa toàn bộ bộ đệm",
      "Purge Individual Paths": "Xóa các đường dẫn cụ thể",
      "Cache Level Settings": "Cài đặt cấp độ bộ nhớ đệm",
      "Determine how much of your website's static contents Cloudflare will cache at the edge.": "Xác định lượng nội dung tĩnh của trang web mà Cloudflare sẽ lưu trữ ở biên.",
      "Global Cache Hit Ratio (24h)": "Tỷ lệ truy cập bộ đệm toàn cầu (24 giờ)",
      "Auto Minify Codes": "Tự động thu gọn mã (Auto Minify)",
      "Remove unnecessary characters (such as comments and whitespaces) from web page source code to reduce transfer size.": "Loại bỏ các ký tự không cần thiết (chẳng hạn như chú thích và khoảng trắng) khỏi mã nguồn trang web để giảm kích thước truyền tải.",
      "HTML Minification": "Thu gọn HTML",
      "CSS Minification": "Thu gọn CSS",
      "JavaScript Minification": "Thu gọn JavaScript",
      "Performance Optimization": "Tối ưu hóa hiệu suất",
      "Brotli Compression": "Nén Brotli",
      "Speed up page load times using Brotli compression.": "Tăng tốc thời gian tải trang bằng công nghệ nén Brotli.",
      "Rocket Loader™": "Rocket Loader™",
      "Improve paint times for pages containing JavaScript.": "Cải thiện thời gian hiển thị cho các trang có chứa JavaScript.",
      "Simulated Performance Score Boost": "Điểm hiệu suất tăng thêm (Mô phỏng)",
      "Global Load Balancer & Origin Pools": "Cân bằng tải toàn cầu & Các nhóm máy chủ gốc",
      "Distribute request traffic across multiple origin servers with active health checking.": "Phân phối lưu lượng truy cập trên nhiều máy chủ gốc với chức năng kiểm tra sức khỏe hoạt động.",
      "Create Balancer": "Tạo bộ cân bằng tải",
      "Origin Pool Name": "Tên nhóm máy chủ gốc",
      "Endpoint Target": "Đích cuối của điểm cuối",
      "Health Path Check": "Đường dẫn kiểm tra sức khỏe",
      "Pool status": "Trạng thái nhóm",
      "URL Redirect Page Rules": "Quy tắc chuyển hướng trang URL",
      "Map request paths to new target URLs using 301 Permanent or 302 Temporary redirects.": "Ánh xạ các đường dẫn yêu cầu tới các URL đích mới bằng chuyển hướng 301 Vĩnh viễn hoặc 302 Tạm thời.",
      "Add Page Rule": "Thêm quy tắc trang",
      "Source Route Match": "Khớp đường dẫn nguồn",
      "Destination Route Target": "Đích đến đường dẫn đích",
      "Redirect Type": "Loại chuyển hướng",
      "Rule status": "Trạng thái quy tắc"
    },
    dash_analytics: {
      "Analytics & Logs": "Phân tích & Nhật ký",
      "Web Traffic Analytics": "Phân tích lưu lượng truy cập Web",
      "Real-time overview of visitor traffic, request volume, and bandwidth performance.": "Tổng quan thời gian thực về lượng khách truy cập, khối lượng yêu cầu và hiệu suất băng thông.",
      "Select Domain": "Chọn tên miền",
      "Summary Metrics (Last 24 Hours)": "Các chỉ số tóm tắt (24 giờ qua)",
      "Total Requests": "Tổng số yêu cầu",
      "Unique Visitors": "Khách truy cập duy nhất",
      "Data Transferred": "Dữ liệu đã truyền",
      "Page Views": "Lượt xem trang",
      "Traffic Volume (Requests vs Visitors)": "Khối lượng lưu lượng (Yêu cầu so với Khách truy cập)",
      "Requests (line)": "Yêu cầu (đường)",
      "Visitors (bar)": "Khách truy cập (cột)",
      "Web requests": "Yêu cầu Web",
      "Unique visitors": "Khách truy cập duy nhất",
      "Traffic by Country / Region": "Lưu lượng truy cập theo Quốc gia / Khu vực",
      "Top sources of geographic traffic requests to your domains.": "Nguồn lưu lượng truy cập địa lý hàng đầu gửi yêu cầu đến các tên miền của bạn.",
      "Country / Region": "Quốc gia / Khu vực",
      "United States": "Hoa Kỳ",
      "Singapore": "Singapore",
      "Germany": "Đức",
      "Vietnam": "Việt Nam",
      "Japan": "Nhật Bản",
      "Percentage": "Tỷ lệ phần trăm"
    },
    dash_security: {
      "WAF & Application Security": "WAF & Bảo mật ứng dụng",
      "Configure Web Application Firewall (WAF), review threat analytics, or setup CAPTCHA Turnstile widgets.": "Cấu hình Tường lửa ứng dụng Web (WAF), xem phân tích mối đe dọa hoặc thiết lập Turnstile CAPTCHA.",
      "WAF Rules": "Quy tắc WAF",
      "Threat Analytics": "Phân tích mối đe dọa",
      "WAF Rules & Firewall Policies": "Các quy tắc WAF & Chính sách tường lửa",
      "Block, challenge, or log incoming web requests matching specific criteria.": "Chặn, thử thách hoặc ghi nhật ký các yêu cầu web đến khớp với các tiêu chí cụ thể.",
      "Add firewall rule": "Thêm quy tắc tường lửa",
      "Search rules...": "Tìm kiếm các quy tắc...",
      "Rule Name": "Tên quy tắc",
      "Expression / Criteria": "Biểu thức / Tiêu chí",
      "Action": "Hành động",
      "Enabled": "Đã bật",
      "Block": "Chặn",
      "Challenge": "Thử thách (JS)",
      "Log": "Ghi nhật ký",
      "Threat Intel & Analytics": "Thông tin & Phân tích mối đe dọa",
      "Visual display of blocked traffic events and DDoS mitigation activity.": "Hiển thị trực quan các sự kiện lưu lượng bị chặn và hoạt động giảm thiểu DDoS.",
      "Events Mitigated": "Các sự kiện đã được giảm thiểu",
      "DDoS Threats Blocked": "Các mối đe dọa DDoS bị chặn",
      "Security Insight Score": "Điểm thông tin bảo mật",
      "Excellent": "Xuất sắc",
      "Mitigated Security Events": "Các sự kiện bảo mật được giảm thiểu"
    },
    dash_workers: {
      "Workers & Pages": "Workers & Pages",
      "Deploy serverless code, deploy static sites via Git workflows, or manage global Cron Triggers.": "Triển khai mã nguồn serverless, triển khai trang web tĩnh thông qua quy trình Git hoặc quản lý Trình kích hoạt Cron toàn cầu.",
      "Create Application": "Tạo ứng dụng",
      "Serverless Functions": "Hàm Serverless",
      "Static Sites": "Trang web tĩnh",
      "Cron Triggers": "Trình kích hoạt Cron",
      "Manage serverless scripts running directly on the edge.": "Quản lý các kịch bản serverless chạy trực tiếp trên biên.",
      "Status": "Trạng thái",
      "Requests (24h)": "Yêu cầu (24 giờ)",
      "Active": "Hoạt động",
      "Deploy static frontends using Cloudflare global CDN.": "Triển khai các giao diện tĩnh sử dụng mạng lưới CDN toàn cầu của Cloudflare.",
      "Repository": "Kho lưu trữ",
      "Branch": "Nhánh",
      "Last Deploy": "Lần triển khai cuối",
      "Configure automated timers to invoke serverless logic periodically.": "Cấu hình bộ hẹn giờ tự động để gọi logic serverless định kỳ.",
      "Interval": "Khoảng thời gian",
      "Every minute": "Mỗi phút",
      "Every 5 minutes": "Mỗi 5 phút",
      "Every hour": "Mỗi giờ",
      "Daily": "Hàng ngày",
      "Target Script": "Kịch bản đích"
    },
    dash_storage: {
      "Storage & Databases": "Lưu trữ & Cơ sở dữ liệu",
      "Store global application data using key-value stores, relational SQL, or large object buckets.": "Lưu trữ dữ liệu ứng dụng toàn cầu bằng kho dữ liệu key-value, SQL quan hệ hoặc kho chứa đối tượng lớn.",
      "KV Namespace": "Không gian tên KV",
      "SQL Database": "Cơ sở dữ liệu SQL",
      "Object Bucket": "Kho chứa đối tượng",
      "Namespace ID": "ID không gian tên",
      "Keys Count": "Số lượng khóa",
      "Database Name": "Tên cơ sở dữ liệu",
      "Size": "Kích thước",
      "Bucket Name": "Tên kho chứa R2",
      "Objects Count": "Số lượng đối tượng",
      "Create Namespace": "Tạo không gian tên",
      "Create Database": "Tạo cơ sở dữ liệu",
      "Create Bucket": "Tạo kho chứa R2",
      "Active": "Hoạt động",
      "Storage": "Lưu trữ",
      "Manage storage": "Quản lý lưu trữ"
    },
    dash_ai: {
      "Workers AI Hub": "Trung tâm Workers AI",
      "Run serverless AI models on Cloudflare GPU network. Connect to LLMs, image generation, and translation instantly.": "Chạy các mô hình AI serverless trên mạng GPU của Cloudflare. Kết nối với LLM, tạo hình ảnh và dịch thuật tức thì.",
      "Chat with Model": "Trò chuyện với Mô hình AI",
      "Run Inference": "Chạy suy luận AI",
      "Select AI Model": "Chọn mô hình AI",
      "System Prompt": "Gợi ý hệ thống (System prompt)",
      "User Input": "Đầu vào của người dùng",
      "Generate Response": "Tạo phản hồi AI",
      "Generation Progress": "Tiến trình tạo",
      "Result Output": "Kết quả đầu ra",
      "Ready for inference.": "Sẵn sàng chạy suy luận AI.",
      "Running AI inference...": "Đang chạy suy luận AI..."
    },
    dash_media: {
      "Media & Images": "Truyền thông & Hình ảnh",
      "Optimize images and stream video content across the global Anycast network.": "Tối ưu hóa hình ảnh và truyền phát nội dung video trên mạng Anycast toàn cầu.",
      "Stream Videos": "Stream Videos (Video trực tuyến)",
      "Optimize Images": "Tối ưu hóa hình ảnh",
      "Video Title": "Tiêu đề Video",
      "Duration": "Thời lượng",
      "Uploaded": "Đã tải lên",
      "File Size": "Kích thước tệp",
      "Status": "Trạng thái",
      "Ready": "Sẵn sàng",
      "Processing": "Đang xử lý",
      "Image Name": "Tên hình ảnh",
      "Dimensions": "Kích thước (pixel)",
      "Format": "Định dạng",
      "Compression Ratio": "Tỷ lệ nén"
    },
    dash_zero_trust: {
      "Zero Trust Services": "Dịch vụ Zero Trust",
      "Configure edge secure gateway, coordinate remote access control policies, and audit network logs.": "Cấu hình cổng bảo mật biên, điều phối các chính sách kiểm soát truy cập từ xa và kiểm tra nhật ký mạng.",
      "Access Control Policies": "Chính sách kiểm soát truy cập",
      "Audit logs": "Nhật ký kiểm tra",
      "Search policies...": "Tìm kiếm chính sách...",
      "Policy Name": "Tên chính sách",
      "Target Application": "Ứng dụng đích",
      "Allowed Groups": "Các nhóm được phép",
      "Action": "Hành động",
      "Allow": "Cho phép",
      "Bypass": "Bỏ qua",
      "Audit Activity Logs": "Nhật ký kiểm tra hoạt động",
      "Timestamp": "Dấu thời gian",
      "Actor": "Người thực hiện",
      "Resource": "Tài nguyên",
      "Success": "Thành công",
      "Failed": "Thất bại"
    },
    dash_manage_account: {
      "Manage Account": "Quản lý tài khoản",
      "Configure account settings, manage members, billing subscriptions, API tokens, and view audits.": "Cấu hình tài khoản, quản lý thành viên, thanh toán, token API và xem nhật ký.",
      "Members": "Thành viên",
      "Billing": "Thanh toán",
      "Audit Logs": "Nhật ký kiểm tra",
      "Invite Member": "Mời thành viên",
      "Search members...": "Tìm kiếm thành viên...",
      "Email Address": "Địa chỉ Email",
      "Role": "Vai trò",
      "Status": "Trạng thái",
      "Administrator": "Quản trị viên",
      "Developer": "Lập trình viên",
      "Billing Admin": "Quản trị thanh toán",
      "Active": "Hoạt động",
      "Pending Invitation": "Đang chờ chấp nhận",
      "Invite": "Mời",
      "Invite members": "Mời thành viên",
      "Billing Subscriptions": "Gói thanh toán hiện tại",
      "Invoice Number": "Số hóa đơn",
      "Date": "Ngày thanh toán",
      "Amount": "Số tiền",
      "Paid": "Đã thanh toán",
      "Search audit logs...": "Tìm kiếm nhật ký kiểm tra...",
      "Event Name": "Tên sự kiện",
      "IP Address": "Địa chỉ IP"
    },
    dash_investigate: {
      "Investigate & Threat Center": "Trung tâm Điều tra & Mối đe dọa",
      "Analyze threat intelligence databases, run scanning actions, and review reputation profiles.": "Phân tích cơ sở dữ liệu mối đe dọa, chạy quét và xem hồ sơ uy tín.",
      "Run Threat Scan": "Chạy Quét mối đe dọa",
      "Domain or IP Address": "Tên miền hoặc Địa chỉ IP",
      "Scan": "Quét",
      "Scanning in progress...": "Đang quét..."
    },
    dash_settings: {
      "Account Settings": "Cấu hình tài khoản",
      "Manage account configurations, notification rules, and preferences.": "Quản lý cấu hình tài khoản, quy tắc thông báo và các tùy chọn khác.",
      "Account Name": "Tên tài khoản",
      "Notification Settings": "Cài đặt thông báo"
    },
    dash_profile: {
      "User Profile": "Hồ sơ người dùng",
      "Manage personal account profile, authentication preferences, and active sessions.": "Quản lý hồ sơ cá nhân, cấu hình xác thực và phiên hoạt động.",
      "Email Address": "Địa chỉ Email",
      "Language Preference": "Ngôn ngữ ưa thích",
      "Change Password": "Đổi mật khẩu"
    },
    dash_plans: {
      "Plans & Pricing": "Các gói dịch vụ & Giá cả",
      "Review current plans or upgrade to access advanced delivery, performance, and security features.": "Xem xét các gói hiện tại hoặc nâng cấp để truy cập các tính năng nâng cao.",
      "Free Plan": "Gói miễn phí",
      "Pro Plan": "Gói Pro",
      "Business Plan": "Gói Business",
      "Enterprise Plan": "Gói Enterprise",
      "Current Plan": "Gói hiện tại",
      "Upgrade": "Nâng cấp"
    },
    dash_recents: {
      "Recent Activity": "Hoạt động gần đây",
      "Timeline of recent actions and status changes on your account resources.": "Dòng thời gian của các hoạt động và thay đổi trạng thái tài nguyên tài khoản."
    }
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const updateLang = () => {
      const stored = localStorage.getItem("preferred_language");
      if (stored) {
        setLanguageState(stored.startsWith("vi") ? "vi" : "en");
      } else if (localStorage.language) {
        setLanguageState(localStorage.language.startsWith("vi") ? "vi" : "en");
      }
    };

    const timer = setTimeout(updateLang, 0);

    const handleStorageChange = () => {
      const updated = localStorage.getItem("preferred_language");
      if (updated) {
        setLanguageState(updated.startsWith("vi") ? "vi" : "en");
      }
    };

    window.addEventListener("storage", handleStorageChange);
    return () => {
      clearTimeout(timer);
      window.removeEventListener("storage", handleStorageChange);
    };
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    const fullCode = lang === "vi" ? "vi-VN" : "en-US";
    localStorage.setItem("preferred_language", fullCode);
    localStorage.language = lang;
    window.dispatchEvent(new Event("storage"));
  };

  const t = (key: string, section: string = "common"): string => {
    const sectDict = TRANSLATIONS[language]?.[section];
    if (sectDict && sectDict[key] !== undefined) {
      return sectDict[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
