-- 1. Create table crawler_tasks if not exists
CREATE TABLE IF NOT EXISTS public.crawler_tasks (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    platform text NOT NULL,
    command text NOT NULL,
    target text NOT NULL,
    max_count integer DEFAULT 50,
    status text DEFAULT 'pending'::text NOT NULL,
    priority text DEFAULT 'normal'::text,
    scheduled_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    error_message text,
    CONSTRAINT check_task_status CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'cancelled'::text, 'scheduled'::text])),
    CONSTRAINT check_task_priority CHECK (priority = ANY (ARRAY['critical'::text, 'high'::text, 'normal'::text, 'low'::text]))
);

-- 2. Create table crawler_logs if not exists
CREATE TABLE IF NOT EXISTS public.crawler_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id uuid REFERENCES public.crawler_tasks(id) ON DELETE CASCADE NOT NULL,
    level text NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. Create table crawled_posts if not exists
CREATE TABLE IF NOT EXISTS public.crawled_posts (
    id text NOT NULL PRIMARY KEY,
    platform text NOT NULL,
    author_id text,
    platform_id text,
    caption text,
    cover_url text,
    media_urls text[],
    stats jsonb,
    raw jsonb,
    published_at timestamp with time zone,
    crawled_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 4. Create table crawled_authors if not exists
CREATE TABLE IF NOT EXISTS public.crawled_authors (
    id text NOT NULL PRIMARY KEY,
    platform_uid text,
    nickname text,
    platform text NOT NULL,
    gender text DEFAULT 'unknown'::text,
    description text,
    fans_count integer DEFAULT 0,
    follows_count integer DEFAULT 0,
    ip_location text,
    avatar_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 5. Create RPC function for safe bulk tasks insertion
CREATE OR REPLACE FUNCTION public.create_crawler_tasks(
  p_tasks jsonb
) RETURNS jsonb AS $$
DECLARE
  v_task jsonb;
  v_inserted_count int := 0;
  v_skipped_count int := 0;
  v_errors text[] := '{}';
  v_platform text;
  v_command text;
  v_target text;
  v_max_count int;
  v_priority text;
  v_result jsonb;
BEGIN
  -- Check limit 50 tasks
  IF jsonb_array_length(p_tasks) > 50 THEN
    RAISE EXCEPTION 'Số lượng nhiệm vụ vượt quá giới hạn 50 trong một lần tạo.';
  END IF;

  FOR v_task IN SELECT * FROM jsonb_array_elements(p_tasks) LOOP
    v_platform := v_task->>'platform';
    v_command := v_task->>'command';
    v_target := trim(v_task->>'target');
    v_max_count := coalesce((v_task->>'max_count')::int, 50);
    v_priority := coalesce(v_task->>'priority', 'normal');

    IF v_target = '' OR v_target IS NULL THEN
      v_skipped_count := v_skipped_count + 1;
      CONTINUE;
    END IF;

    -- Atomic check
    IF EXISTS (
      SELECT 1 FROM public.crawler_tasks 
      WHERE platform = v_platform 
        AND command = v_command 
        AND lower(trim(target)) = lower(v_target)
        AND status IN ('pending', 'running')
    ) THEN
      v_skipped_count := v_skipped_count + 1;
      v_errors := array_append(v_errors, format('Nhiệm vụ "%s" cho %s đang chạy hoặc đang chờ.', v_target, v_platform));
    ELSE
      INSERT INTO public.crawler_tasks (platform, command, target, max_count, status, priority)
      VALUES (v_platform, v_command, v_target, v_max_count, 'pending', v_priority);
      v_inserted_count := v_inserted_count + 1;
    END IF;
  END LOOP;

  v_result := jsonb_build_object(
    'inserted_count', v_inserted_count,
    'skipped_count', v_skipped_count,
    'errors', to_jsonb(v_errors)
  );
  RETURN v_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
